import React from "react";
import { notFound } from "next/navigation";
import ReduxProvider from "@/redux/provider";
import NextTopLoader from "nextjs-toploader";
import { NextIntlClientProvider } from "next-intl";

import RouteGuard from "@/app/hooks/RouteGuard";

import Header from "@/components/molecules/header/Header";
import Footer from "@/components/molecules/footer/Footer";

import "../styles/globals.css";

export const metadata = {
  title: "Missafir Beta",
  description: "Generated by missafir tech"
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "tr" }, { locale: "hr" }];
}

const RootLayout = async ({ children, params: { lang } }: any) => {
  let messages;
  try {
    messages = (await import(`../../locales/${lang}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={lang}>
      <head>
        <meta
          name="google-site-verification"
          content="L7xAcVXBfqNFTj_VSqCaZU-gKHXK-T7chpoLJZE3FYU"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        />
      </head>
      <body className="font-mi-sans" suppressHydrationWarning={true}>
        <NextTopLoader color="#D01E50" showSpinner={false} />
        <ReduxProvider>
          <NextIntlClientProvider locale={lang} messages={messages}>
            <div id="drawer-container"></div>
            <Header lang={lang} />
            <main className="min-h-screen">
              <RouteGuard>{children}</RouteGuard>
            </main>
            <Footer />
          </NextIntlClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
