import React from "react";
import { Metadata } from "next";
import dynamic from "next/dynamic";
import { notFound } from "next/navigation";
import ReduxProvider from "@/redux/provider";
import { NextIntlClientProvider } from "next-intl";

import { UIProvider } from "@/app/UIProvider";
import RouteGuard from "@/app/hooks/RouteGuard";

import HandleInterceptor from "@/components/atoms/handleInterceptor/HandleInterceptor";
export const revalidate = 3600; 
import "../styles/globals.css";
// export const dynamic = "force-dynamic";

const Header: any = dynamic(
  () => import("@/components/molecules/header/Header"),
  {
    ssr: false
  }
);

const Footer: any = dynamic(
  () => import("@/components/molecules/footer/Footer"),
  {
    ssr: false
  }
);

export const metadata: Metadata = {
  title: "Missafir Beta",
  description: "Generated by Missafir Tech",
  viewport:
    "width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "tr" }, { locale: "hr" }];
}

const RootLayout = async ({ children, params: { lang } }: any) => {
  let messages;
  try {
    messages = (await import(`../../locales/${lang}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={lang}>
      <head>
        <meta
          name="google-site-verification"
          content="L7xAcVXBfqNFTj_VSqCaZU-gKHXK-T7chpoLJZE3FYU"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        />
      </head>
      <body className="font-mi-sans" suppressHydrationWarning={true}>
        <UIProvider>
          <ReduxProvider>
            <NextIntlClientProvider locale={lang} messages={messages}>
              <div id="drawer-container"></div>
              <HandleInterceptor />
              <Header lang={lang} />
              <main className="min-h-screen">
                <RouteGuard>{children}</RouteGuard>
              </main>
              <Footer lang={lang} />
            </NextIntlClientProvider>
          </ReduxProvider>
        </UIProvider>
      </body>
    </html>
  );
};

export default RootLayout;
