import React, { ReactNode } from "react";

import Header from "@/components/molecules/header/Header";
import Footer from "@/components/molecules/footer/Footer";

import "./styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
