import React, { ReactNode } from "react";

import Header from "@/components/molecules/header/Header";
import Footer from "@/components/molecules/footer/Footer";

import "./styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html>
      <head>
        <title>Missafirv3 Beta</title>
        <meta
          name="google-site-verification"
          content="L7xAcVXBfqNFTj_VSqCaZU-gKHXK-T7chpoLJZE3FYU"
        />
      </head>
      <body className="font-mi-sans" suppressHydrationWarning={true}>
        <div id="drawer-container"></div>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
